export default ( async () => {
	const stylistic = await import( `file:///${ process.env.APPDATA }/npm/node_modules/@stylistic/eslint-plugin/dist/index.js` );

	const lineMaxLength = 220;
	const lineMaxStatement = 3;
	const argsIgnorePattern = "^_";
	const varsIgnorePattern = `(${ [
		"^gsui[0-9A-Z]",
		"^gswa[A-Z]",
		"^gsco[A-Z]",
		"^GSU[a-zA-Z]",
		"^GSEV_[A-Z]",
		"^lg$",
		"^GSData$",
		"^___$",
	].join( "|" ) })`;

	return [
		{
			files: [ "**/*.js" ],
			languageOptions: {
				sourceType: "script",
			},
			plugins: {
				"@stylistic": stylistic.default,
			},
			rules: {
				"yoda":                            [ "error", "never", { exceptRange: true } ],
				"strict":                          [ "error", "global" ],
				"eqeqeq":                          [ "error", "always" ],
				"no-var":                          [ "error" ],
				"one-var":                         [ "error", "never" ],
				"no-empty":                        [ "error" ],
				"dot-notation":                    [ "error" ],
				"prefer-const":                    [ "error" ],
				"prefer-spread":                   [ "error" ],
				"no-lonely-if":                    [ "error" ],
				"no-else-return":                  [ "error" ],
				"no-unused-vars":                  [ "error", { argsIgnorePattern, varsIgnorePattern, ignoreRestSiblings: true } ],
				"prefer-template":                 [ "error" ],
				"no-empty-function":               [ "error", { allow: [ "arrowFunctions", "methods" ] } ],
				"no-param-reassign":               [ "error", { props: false } ],
				"prefer-rest-params":              [ "error" ],
				"operator-assignment":             [ "error", "always" ],
				"prefer-object-spread":            [ "error" ],
				"prefer-arrow-callback":           [ "error" ],
				"require-unicode-regexp":          [ "error" ],
				"prefer-exponentiation-operator":  [ "error" ],
				"no-unused-private-class-members": [ "error" ],

				// .....................................................................
				"curly":            [ "error", "all" ],
				"object-shorthand": [ "error", "always", { avoidExplicitReturnArrows: true } ],

				// checks
				// .....................................................................
				"use-isnan":            [ "error" ],
				"valid-typeof":         [ "error" ],
				"no-const-assign":      [ "error" ],
				"no-dupe-else-if":      [ "error" ],
				"constructor-super":    [ "error" ],
				"no-duplicate-case":    [ "error" ],
				"no-case-declarations": [ "error" ],
				"no-this-before-super": [ "error" ],

				// no-*
				// .....................................................................
				"no-eval":                      [ "error" ],
				"no-void":                      [ "error" ],
				"no-with":                      [ "error" ],
				"no-proto":                     [ "error" ],
				"no-labels":                    [ "error" ],
				"no-caller":                    [ "error" ],
				"no-debugger":                  [ "error" ],
				"no-new-func":                  [ "error" ],
				"no-dupe-args":                 [ "error" ],
				"no-dupe-keys":                 [ "error" ],
				"no-multi-str":                 [ "error" ],
				"no-obj-calls":                 [ "error" ],
				"no-redeclare":                 [ "error", { builtinGlobals: true } ],
				"no-extra-bind":                [ "error" ],
				"no-script-url":                [ "error" ],
				"no-undef-init":                [ "error" ],
				"no-unreachable":               [ "error" ],
				"no-lone-blocks":               [ "error" ],
				"no-new-wrappers":              [ "error" ],
				"no-return-await":              [ "error" ],
				"no-class-assign":              [ "error" ],
				"no-self-compare":              [ "error" ],
				"no-octal-escape":              [ "error" ],
				"no-implied-eval":              [ "error" ],
				"no-useless-call":              [ "error" ],
				"no-global-assign":             [ "error" ],
				"no-empty-pattern":             [ "error" ],
				"no-await-in-loop":             [ "error" ],
				"no-extend-native":             [ "error" ],
				"no-unsafe-finally":            [ "error" ],
				"no-useless-concat":            [ "error" ],
				"no-useless-escape":            [ "error" ],
				"no-useless-rename":            [ "error" ],
				"no-useless-return":            [ "error" ],
				"no-unsafe-negation":           [ "error" ],
				"no-compare-neg-zero":          [ "error" ],
				"no-use-before-define":         [ "error", { functions: true, classes: false, variables: true } ],
				"no-constant-condition":        [ "error" ],
				"no-dupe-class-members":        [ "error" ],
				"no-prototype-builtins":        [ "error" ],
				"no-inner-declarations":        [ "error" ],
				"no-extra-boolean-cast":        [ "error" ],
				"no-unused-expressions":        [ "error", { allowShortCircuit: true, allowTernary: true } ],
				"no-useless-constructor":       [ "error" ],
				"no-useless-computed-key":      [ "error" ],
				"no-irregular-whitespace":      [ "error" ],
				"no-unexpected-multiline":      [ "error" ],
				"no-template-curly-in-string":  [ "error" ],
				"no-unsafe-optional-chaining":  [ "error" ],
				"no-unmodified-loop-condition": [ "error" ],

				// stylistic (plugin)
				// .....................................................................
				"@stylistic/semi":          [ "error", "always" ],
				"@stylistic/semi-style":    [ "error", "last" ],
				"@stylistic/no-extra-semi": [ "error" ],
				// .....................................................................
				"@stylistic/key-spacing":               [ "error", { mode: "minimum" } ],
				"@stylistic/semi-spacing":              [ "error", { before: false, after: true } ],
				"@stylistic/arrow-spacing":             [ "error", { before: true, after: true } ],
				"@stylistic/block-spacing":             [ "error", "always" ],
				"@stylistic/comma-spacing":             [ "error", { before: false, after: true } ],
				"@stylistic/keyword-spacing":           [ "error", { before: true, after: true } ],
				"@stylistic/yield-star-spacing":        [ "error", "before" ],
				"@stylistic/rest-spread-spacing":       [ "error", "never" ],
				"@stylistic/object-curly-spacing":      [ "error", "always" ],
				"@stylistic/switch-colon-spacing":      [ "error", { before: false, after: true } ],
				"@stylistic/template-tag-spacing":      [ "error", "always" ],
				"@stylistic/array-bracket-spacing":     [ "error", "always" ],
				"@stylistic/function-call-spacing":     [ "error", "never" ],
				"@stylistic/generator-star-spacing":    [ "error", { before: true, after: false } ],
				"@stylistic/template-curly-spacing":    [ "error", "always" ],
				"@stylistic/computed-property-spacing": [ "error", "always" ],
				// .....................................................................
				"@stylistic/array-element-newline": [ "error", "consistent" ],
				"@stylistic/comma-dangle":          [ "error", {
					"arrays":           "always-multiline",
					"objects":          "always-multiline",
					"imports":          "always-multiline",
					"exports":          "always-multiline",
					"functions":        "only-multiline",
					"importAttributes": "always-multiline",
					"dynamicImports":   "always-multiline",
					"enums":            "always-multiline",
					"generics":         "always-multiline",
					"tuples":           "always-multiline",
				} ],
				"@stylistic/curly-newline":               [ "error", { consistent: true, multiline: true, minElements: 2 } ],
				"@stylistic/dot-location":                [ "error", "property" ],
				"@stylistic/indent-binary-ops":           [ "error", "tab" ],
				"@stylistic/lines-between-class-members": [ "error", { enforce: [
					{ blankLine: "never", prev: "field", next: "field" },
				] } ],
				"@stylistic/max-len":                          [ "error", { code: lineMaxLength, tabWidth: 4 } ],
				"@stylistic/max-statements-per-line":          [ "error", { max: lineMaxStatement } ],
				"@stylistic/no-multiple-empty-lines":          [ "error", { max: 1, maxEOF: 0 } ],
				"@stylistic/nonblock-statement-body-position": [ "error", "below" ],
				"@stylistic/one-var-declaration-per-line":     [ "error", "always" ],
				"@stylistic/operator-linebreak":               [ "error", "after", { overrides: { "?": "ignore", ":": "ignore" } } ],
 				"@stylistic/no-mixed-operators":               [ "error", { groups: [ [ "&", "|", "^", "~", "<<", ">>", ">>>" ], [ "&&", "||" ] ] } ],
				"@stylistic/wrap-iife":                        [ "error", "inside" ],
				// .....................................................................
				"@stylistic/indent":                          [ "error", "tab", { SwitchCase: 1, flatTernaryExpressions: true, ignoredNodes: [ "AssignmentExpression > .right" ] } ],
				"@stylistic/quotes":                          [ "error", "double" ],
				"@stylistic/no-tabs":                         [ "error", { allowIndentationTabs: true } ],
				"@stylistic/new-parens":                      [ "error" ],
				"@stylistic/brace-style":                     [ "error", "1tbs", { allowSingleLine: true } ],
				"@stylistic/arrow-parens":                    [ "error", "as-needed" ],
				"@stylistic/no-extra-parens":                 [ "error", "all", { nestedBinaryExpressions: false, returnAssign: false } ],
				"@stylistic/comma-style":                     [ "error", "last" ],
				"@stylistic/quote-props":                     [ "error", "as-needed" ],
				"@stylistic/linebreak-style":                 [ "error", "unix" ],
				// .....................................................................
				"@stylistic/eol-last":                      [ "error", "always" ],
				"@stylistic/padded-blocks":                 [ "error", "never" ],
				"@stylistic/spaced-comment":                [ "error", "always" ],
				"@stylistic/space-in-parens":               [ "error", "always" ],
				"@stylistic/space-infix-ops":               [ "error" ],
				"@stylistic/space-unary-ops":               [ "error", { words: true, nonwords: false } ],
				"@stylistic/no-trailing-spaces":            [ "error" ],
				"@stylistic/space-before-blocks":           [ "error", "always" ],
				"@stylistic/no-mixed-spaces-and-tabs":      [ "error", "smart-tabs" ],
				"@stylistic/space-before-function-paren":   [ "error", "never" ],
				"@stylistic/no-whitespace-before-property": [ "error" ],
				"@stylistic/padding-line-between-statements": [ "error",
					{ blankLine: "always", prev: [ "const", "let" ], next: "*" },
					{ blankLine: "never",  prev: [ "const", "let" ], next: [ "const", "let" ] }
				],
			},
		},
	];
} )();
