export default ( async () => {
	const stylistic = await import( `file:///${ process.env.APPDATA }/npm/node_modules/@stylistic/eslint-plugin/dist/index.js` );

	const files = [
		"gsui*/*.js",
		"src/**/*.js",
	];

	const argsIgnorePattern = "^_";
	const varsIgnorePattern = "^gs(ui|co)[A-Z\d]";

	return [
		{
			files,
			languageOptions: {
				sourceType: "script",
			},
			plugins: {
				"@stylistic": stylistic.default,
			},
			rules: {
				"yoda":                            [ "error", "never", { exceptRange: true } ],
				"strict":                          [ "error", "global" ],
				"eqeqeq":                          [ "error", "always" ],
				"no-var":                          [ "error" ],
				"one-var":                         [ "error", "never" ],
				"no-empty":                        [ "error" ],
				"dot-notation":                    [ "error" ],
				"prefer-const":                    [ "error" ],
				"prefer-spread":                   [ "error" ],
				"no-lonely-if":                    [ "error" ],
				"no-else-return":                  [ "error" ],
				"no-unused-vars":                  [ "error", { argsIgnorePattern, varsIgnorePattern, } ],
				"prefer-template":                 [ "error" ],
				"no-empty-function":               [ "error", { allow: [ "arrowFunctions", "methods" ] } ],
				"no-param-reassign":               [ "error", { props: false } ],
				"prefer-rest-params":              [ "error" ],
				"operator-assignment":             [ "error", "always" ],
				"prefer-object-spread":            [ "error" ],
				"prefer-arrow-callback":           [ "error" ],
				"require-unicode-regexp":          [ "error" ],
				"prefer-exponentiation-operator":  [ "error" ],
				"no-unused-private-class-members": [ "error" ],

				// brackets/braces/parens
				// .....................................................................
				"curly":            [ "error", "all" ],
				"object-shorthand": [ "error", "always", { avoidExplicitReturnArrows: true } ],

				// checks
				// .....................................................................
				"use-isnan":            [ "error" ],
				"valid-typeof":         [ "error" ],
				"no-const-assign":      [ "error" ],
				"no-dupe-else-if":      [ "error" ],
				"constructor-super":    [ "error" ],
				"no-duplicate-case":    [ "error" ],
				"no-case-declarations": [ "error" ],
				"no-this-before-super": [ "error" ],

				// no-*
				// .....................................................................
				"no-eval":                      [ "error" ],
				"no-void":                      [ "error" ],
				"no-with":                      [ "error" ],
				"no-proto":                     [ "error" ],
				"no-labels":                    [ "error" ],
				"no-caller":                    [ "error" ],
				"no-debugger":                  [ "error" ],
				"no-new-func":                  [ "error" ],
				"no-dupe-args":                 [ "error" ],
				"no-dupe-keys":                 [ "error" ],
				"no-multi-str":                 [ "error" ],
				"no-obj-calls":                 [ "error" ],
				"no-redeclare":                 [ "error", { builtinGlobals: true } ],
				"no-extra-bind":                [ "error" ],
				"no-script-url":                [ "error" ],
				"no-undef-init":                [ "error" ],
				"no-unreachable":               [ "error" ],
				"no-lone-blocks":               [ "error" ],
				"no-new-wrappers":              [ "error" ],
				"no-return-await":              [ "error" ],
				"no-class-assign":              [ "error" ],
				"no-self-compare":              [ "error" ],
				"no-octal-escape":              [ "error" ],
				"no-implied-eval":              [ "error" ],
				"no-useless-call":              [ "error" ],
				"no-global-assign":             [ "error" ],
				"no-empty-pattern":             [ "error" ],
				"no-await-in-loop":             [ "error" ],
				"no-extend-native":             [ "error" ],
				"no-unsafe-finally":            [ "error" ],
				"no-useless-concat":            [ "error" ],
				"no-useless-escape":            [ "error" ],
				"no-useless-rename":            [ "error" ],
				"no-useless-return":            [ "error" ],
				"no-unsafe-negation":           [ "error" ],
				"no-compare-neg-zero":          [ "error" ],
				"no-use-before-define":         [ "error", { functions: true, classes: false, variables: true } ],
				"no-constant-condition":        [ "error" ],
				"no-dupe-class-members":        [ "error" ],
				"no-prototype-builtins":        [ "error" ],
				"no-inner-declarations":        [ "error" ],
				"no-extra-boolean-cast":        [ "error" ],
				"no-unused-expressions":        [ "error", { allowShortCircuit: true, allowTernary: true } ],
				"no-useless-constructor":       [ "error" ],
				"no-useless-computed-key":      [ "error" ],
				"no-irregular-whitespace":      [ "error" ],
				"no-unexpected-multiline":      [ "error" ],
				"no-template-curly-in-string":  [ "error" ],
				"no-unsafe-optional-chaining":  [ "error" ],
				"no-unmodified-loop-condition": [ "error" ],

				// stylistic
				// .....................................................................
				"@stylistic/semi":                            [ "error", "always" ],
				"@stylistic/no-tabs":                         [ "error", { allowIndentationTabs: true } ],
				"@stylistic/quotes":                          [ "error", "double" ],
				"@stylistic/indent":                          [ "error", "tab", { SwitchCase: 1, flatTernaryExpressions: true, ignoredNodes: [ "AssignmentExpression > .right" ] } ],
				"@stylistic/new-parens":                      [ "error" ],
				"@stylistic/brace-style":                     [ "error", "1tbs", { allowSingleLine: true } ],
				"@stylistic/arrow-parens":                    [ "error", "as-needed" ],
				"@stylistic/no-extra-parens":                 [ "error", "all", { nestedBinaryExpressions: false, returnAssign: false } ],
				"@stylistic/semi-style":                      [ "error", "last" ],
				"@stylistic/comma-style":                     [ "error", "last" ],
				"@stylistic/quote-props":                     [ "error", "as-needed" ],
				"@stylistic/no-extra-semi":                   [ "error" ],
				"@stylistic/linebreak-style":                 [ "error", "unix" ],
				// .....................................................................
				"@stylistic/eol-last":                        [ "error", "always" ],
				"@stylistic/key-spacing":                     [ "error", { mode: "minimum" } ],
				"@stylistic/arrow-spacing":                   [ "error", { before: true, after: true } ],
				"@stylistic/comma-spacing":                   [ "error", { before: false, after: true } ],
				"@stylistic/padded-blocks":                   [ "error", "never" ],
				"@stylistic/spaced-comment":                  [ "error", "always" ],
				"@stylistic/space-infix-ops":                 [ "error" ],
				"@stylistic/keyword-spacing":                 [ "error", { before: true, after: true } ],
				"@stylistic/space-in-parens":                 [ "error", "always" ],
				"@stylistic/no-trailing-spaces":              [ "error" ],
				"@stylistic/rest-spread-spacing":             [ "error", "never" ],
				"@stylistic/object-curly-spacing":            [ "error", "always" ],
				"@stylistic/switch-colon-spacing":            [ "error", { before: false, after: true } ],
				"@stylistic/array-bracket-spacing":           [ "error", "always" ],
				"@stylistic/function-call-spacing":           [ "error", "never" ],
				"@stylistic/template-curly-spacing":          [ "error", "always" ],
				"@stylistic/no-mixed-spaces-and-tabs":        [ "error", "smart-tabs" ],
				"@stylistic/computed-property-spacing":       [ "error", "always" ],
				"@stylistic/no-whitespace-before-property":   [ "error" ],
				"@stylistic/padding-line-between-statements": [ "error",
				                                                  { blankLine: "always", prev: [ "const", "let" ], next: "*" },
				                                                  { blankLine: "never",  prev: [ "const", "let" ], next: [ "const", "let" ] }
				                                              ],
			},
		},
	];
} )();
