export default {
	rules: {
		"selector-max-id": 2,
		// "selector-max-type": 2,
		// "selector-max-class": 4,
		// "selector-max-universal": 0,
		// "selector-max-attribute": 2,
		"selector-max-combinators": 3,
		// "selector-max-pseudo-class": 3,
		"selector-max-compound-selectors": 4,
		"selector-max-specificity": "2,3,1",
		"declaration-block-single-line-max-declarations": 3,

		"value-no-vendor-prefix": true,
		"at-rule-no-vendor-prefix": true,
		"selector-no-vendor-prefix": true,
		// "property-no-vendor-prefix": [ true, { "ignoreProperties": [ "appearance" ] } ],
		"media-feature-name-no-vendor-prefix": true,

		"color-named": "never",
		// "color-hex-length": "short",
		"function-url-quotes": "always",
		// "length-zero-no-unit": true,
		"number-max-precision": 2,
		// "font-weight-notation": "named-where-possible",
		"font-family-name-quotes": "always-unless-keyword",
		// "declaration-no-important": true,
		"selector-attribute-quotes": "always",
		"keyframe-declaration-no-important": true,
		"selector-pseudo-element-colon-notation": "double",

		"function-name-case": "lower",
		// "value-keyword-case": [ "lower", { "camelCaseSvgKeywords": true } ],
		"selector-type-case": "lower",

		"selector-id-pattern": null,
		"custom-media-pattern": null,
		"keyframes-name-pattern": null,
		"selector-class-pattern": null,
		"custom-property-pattern": null,

		"block-no-empty": true,
		"no-empty-source": true,
		"unit-no-unknown": true,
		"comment-no-empty": true,
		"string-no-newline": true,
		"at-rule-no-unknown": true,
		"color-no-invalid-hex": true,
		// "no-duplicate-selectors": true,
		"selector-type-no-unknown": [ true, { "ignore": [ "custom-elements" ] } ],
		"no-duplicate-at-import-rules": true,
		"media-feature-name-no-unknown": true,
		"font-family-no-duplicate-names": true,
		"no-invalid-double-slash-comments": true,
		"selector-pseudo-class-no-unknown": true,
		"selector-pseudo-element-no-unknown": true,
		"declaration-property-value-no-unknown": true,
		// "shorthand-property-no-redundant-values": true,
		// "declaration-block-no-duplicate-properties": true,
		"function-linear-gradient-no-nonstandard-direction": true,
		// "declaration-block-no-shorthand-property-overrides": true,
		// "declaration-block-no-redundant-longhand-properties": true,

		"declaration-empty-line-before": "never",
		// "custom-property-empty-line-before": "never",
		// "comment-whitespace-inside": "always",
		// "comment-empty-line-before": [ "always", { "ignore": [ "after-comment" ] }],
		// "function-calc-no-unspaced-operator": true,
		// "at-rule-empty-line-before": "always",

		// DEPRECATED
		// .....................................................................
		// "max-empty-lines": 1,
		// "max-line-length": 180,
		// "no-eol-whitespace": true,
		// "no-extra-semicolons": true,
		// "unit-case": "lower",
		// "property-case": "lower",
		// "color-hex-case": "lower",
		// "at-rule-name-case": "lower",
		// "function-max-empty-lines": 0,
		// "selector-max-empty-lines": 0,
		// "value-list-max-empty-lines": 0,
		// "selector-pseudo-class-case": "lower",
		// "selector-pseudo-element-case": "lower",
		// "declaration-bang-space-after": "never",
		// "declaration-bang-space-before": "always",
		// "declaration-colon-space-after": "always-single-line",
		// "declaration-colon-space-before": "never",
		// "no-missing-end-of-source-newline": true,
		// "declaration-block-semicolon-space-after": "always-single-line",
		// "declaration-block-semicolon-space-before": "never",
		// "declaration-block-semicolon-newline-after": "always-multi-line",
		// "declaration-block-semicolon-newline-before": "never-multi-line",
		// "function-whitespace-after": "always",
		// "function-comma-space-after": "always-single-line",
		// "function-comma-space-before": "never",
		// "function-comma-newline-after": "always-multi-line",
		// "value-list-comma-space-after": "always-single-line",
		// "value-list-comma-space-before": "never",
		// "value-list-comma-newline-after": "always-multi-line",
		// "value-list-comma-newline-before": "never-multi-line",
		// "block-opening-brace-space-before": "always",
		// "block-opening-brace-space-after": "always-single-line",
		// "block-opening-brace-newline-after": "always-multi-line",
		// "block-closing-brace-space-before": "always-single-line",
		// "block-closing-brace-space-after": null,
		// "block-closing-brace-newline-after": "always",
		// "block-closing-brace-newline-before": "always-multi-line",
		// "block-closing-brace-empty-line-before": "never",
		// "function-parentheses-space-inside": "always-single-line",
		// "media-query-list-comma-space-after": "always",
		// "media-query-list-comma-space-before": "never",
		// "media-query-list-comma-newline-after": "always",
		// "media-query-list-comma-newline-before": "never-multi-line",
		// "selector-combinator-space-after": "always",
		// "selector-combinator-space-before": "always",
		// "at-rule-semicolon-space-before": "never",
		// "at-rule-semicolon-newline-after": "always",
		// "at-rule-name-space-after": "always",
		// "selector-list-comma-space-after": "always-single-line",
		// "selector-list-comma-space-before": "never",
		// "selector-list-comma-newline-after": "always-multi-line",
		// "selector-list-comma-newline-before": "never-multi-line",
		// "selector-attribute-operator-space-after": "never",
		// "selector-attribute-operator-space-before": "never",
		// "selector-attribute-brackets-space-inside": "always",
		// "selector-pseudo-class-parentheses-space-inside": "always",
		// "linebreaks": "unix",
		// "indentation": "tab",
		// "string-quotes": "double",
		// "number-leading-zero": "never",
		// "number-no-trailing-zeros": true,
		// "declaration-block-trailing-semicolon": "always",
	}
};
